DOOR_DISTRIBUTION equ   $FDD0

POT_ROOM        equ #$20;
NOSE_ROOM       equ #$22;
TRAINING_ROOM   equ #$23;
UPGRADE_ROOM    equ #$24;
SHOP            equ #$25;
BLACK_MARKET    equ #$26;
SPA             equ #$27;

org DOOR_DISTRIBUTION
;w1 - 16 bytes
db POT_ROOM, POT_ROOM
db NOSE_ROOM, NOSE_ROOM, NOSE_ROOM, NOSE_ROOM
db TRAINING_ROOM, TRAINING_ROOM
db UPGRADE_ROOM, UPGRADE_ROOM, UPGRADE_ROOM
db SHOP, SHOP, SHOP, SHOP
db BLACK_MARKET

;w2 - 16 bytes
db POT_ROOM, POT_ROOM
db NOSE_ROOM, NOSE_ROOM, NOSE_ROOM
db TRAINING_ROOM, TRAINING_ROOM
db UPGRADE_ROOM, UPGRADE_ROOM
db SHOP, SHOP, SHOP
db BLACK_MARKET, BLACK_MARKET
db SPA, SPA

;w3 - 16 bytes
db NOSE_ROOM, NOSE_ROOM, NOSE_ROOM
db TRAINING_ROOM, TRAINING_ROOM, TRAINING_ROOM
db UPGRADE_ROOM, UPGRADE_ROOM
db SHOP, SHOP, SHOP
db BLACK_MARKET, BLACK_MARKET
db SPA, SPA, SPA